development:
  adapter: postgresql
  encoding: unicode
  database: instapic_dev
  pool: 5
  username: santoshturamari
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: instapic_test
  pool: 5
  username: santoshturamari
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: instapic_production
  pool: 5
  username: santoshturamari
  password:

